# Generated by Django 5.2.4 on 2025-09-12 14:52

import courses.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_alter_course_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to=courses.models.lesson_content_path),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='file_upload',
            field=models.FileField(blank=True, null=True, upload_to=courses.models.lesson_content_path),
        ),
    ]
