# Generated by Django 5.2.4 on 2025-09-12 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_lesson_video_alter_lesson_file_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='content_type',
            field=models.CharField(choices=[('text', 'Text content'), ('videourl', 'Video URL'), ('video', 'Video content'), ('file', 'File content')], default='text', max_length=50),
        ),
    ]
